services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.4
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_BROKER_ID=1

  simulator:
    build:
      context: ./simulator
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    restart: on-failure

  decoder:
    build:
      context: ./decoder-publisher
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    restart: on-failure

  consumer:
    build:
      context: ./consumer
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - KAFKA_TOPIC=market.ticks
    restart: on-failure