global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # placeholders: streamer (Python) and backend (FastAPI) should expose /metrics
  - job_name: 'streamer'
    static_configs:
      - targets: ['streamer:8000']

  - job_name: 'dashboard-backend'
    static_configs:
      - targets: ['dashboard-backend:8000']

  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:8081']
